versioned_docs/version-1.0/language/access-control.md
versioned_docs/version-1.0/language/attachments.mdx
versioned_docs/version-1.0/language/composite-types.mdx
versioned_docs/version-1.0/language/functions.mdx
versioned_docs/version-1.0/language/resources.mdx

Work towards https://github.com/onflow/cadence-lang.org/issues/26

Misc documentation improvements

---

versioned_docs/version-1.0/language/values-and-types.mdx

Part of https://github.com/onflow/cadence-lang.org/issues/26

add documentation for new string functions

---

versioned_docs/version-1.0/language/built-in-functions.mdx

- generalize output type to all fixed-size unsigned integers
- add modulo optional argument

`revertibleRandom` updates

---

docs/cadence-migration-guide.md
docs/json-cadence-spec.md
docusaurus.config.js
src/theme/AnnouncementBar/CloseButton/index.js
src/theme/AnnouncementBar/CloseButton/styles.module.css
src/theme/AnnouncementBar/Content/index.js
src/theme/AnnouncementBar/Content/styles.module.css
src/theme/AnnouncementBar/index.js
src/theme/AnnouncementBar/styles.module.css

Cadence 1.0 migration header warning
Cadence migration guide
https://cadence-lang-org-git-nialexsan-cadence-migration-onflow.vercel.app/docs/cadence-migration-guide

cadence migration guide

---

docs/cadence_migration_guide/index.md

Adding actionable information that devs can use to start changing their code.

Update Migration Guide

---

docs/language/contract-updatability.md

Closes https://github.com/onflow/cadence/issues/3155

Add section to contract updatability about 1.0 upgrades

---

docs/cadence_migration_guide/staging-guide.mdx

adding the staging contract migration guide here

add staging migration guide

---

docs/cadence_migration_guide/emulator-state-migration-guide.mdx
docs/cadence_migration_guide/staging-guide.mdx

add fixes so that capitalization makes sense

title and sidebar to correct format for staging migration guide

---

docs/cadence_migration_guide/type-annotations-guide.mdx
versioned_docs/version-1.0/cadence_migration_guide/index.md
versioned_docs/version-1.0/cadence_migration_guide/staging-guide.mdx
versioned_docs/version-1.0/cadence_migration_guide/type-annotations-guide.mdx

- Synchronize content
- Document account types

Improve Cadence 1.0 migration guide

---

docs/cadence_migration_guide/staging-guide.mdx

Add the `is-validated` step into the staging guide. https://github.com/onflow/docs/pull/697

update staging guide to include validation

---

docs/language/contract-updatability.md

H1 does not show up in sidebar

Fix header level in contract updatability documentation

---

versioned_docs/version-1.0/language/environment-information.md

add info regarding 600 height limit based on
https://github.com/onflow/flow-go/pull/5607#discussion_r1544892228

getBlock height limit

---

versioned_docs/version-1.0/language/access-control.md

Noticed a few grammatical/stylistic/semantic errors here, so fixing them.

Clean up entitlements docs a bit

---

docusaurus.config.js

Issue: https://github.com/onflow/docs/issues/781

Update banner text

---

versioned_docs/version-1.0/cadence-migration-guide/type-annotations-guide.mdx

Closes https://github.com/onflow/cadence/issues/3362

Update section about validator entitlement computation

---

versioned_docs/version-1.0/language/contract-updatability.md

Close https://github.com/onflow/cadence/issues/3210

Document new `#removedType` pragma

---

docs/language/contract-updatability.md

Address https://github.com/onflow/cadence-lang.org/pull/108#discussion_r1621314265

Improve explanation on interface removal restriction

---

versioned_docs/version-1.0/cadence-migration-guide/staging-guide.mdx

issue https://github.com/onflow/docs/issues/796
provide mainnet instructions instead of testnet ones

[migration] change to say mainnet instead of testnet

---

versioned_docs/version-1.0/language/core-events.md

making the doc consistent with changes coming in https://github.com/onflow/cadence/pull/3204

added new fields to AccountKeyAdded event

---

versioned_docs/version-1.0/cadence-migration-guide/index.md

Work towards https://github.com/onflow/docs/issues/819
Now that https://github.com/onflow/flow-cli/pull/1355 got merged, the installation command needs to be updated.
Are there any other places that need to be updated?

Update command for CLI installation

---

versioned_docs/version-1.0/cadence-migration-guide/emulator-state-migration-guide.mdx

Issue: https://github.com/onflow/docs/issues/819

Remove feature branch

---

versioned_docs/version-1.0/cadence-migration-guide/staging-guide.mdx

Updates the staging guide to have the correct CLI commands for staging

Updates staging commands

---

docs/language/contract-updatability.md

Closes https://github.com/onflow/cadence/issues/2046

Document valid changes for events during contract-updates

---

docs/tutorial/06-fungible-tokens.md
docs/tutorial/07-marketplace-setup.md
docs/tutorial/08-marketplace-compose.md

update playground link

---

docs/language/accounts/capabilities.mdx

Update account capabilities type definitions

---

docs/design-patterns.md

Fix links to locked tokens contract

---

docs/design-patterns.md

Add section for revocation of capability

---

docs/design-patterns.md

Add examples for publishing and claiming capability

---

docs/solidity-to-cadence.md

Update solidity-to-cadence for Cadence 1.0

---

docusaurus.config.js
package-lock.json
package.json
static/hotjar.js

closes: https://github.com/onflow/cadence/issues/3639
updated node packages and dependencies, added hotjar analytics tool to head tag.

Add hotjar analytics

---

docs/measuring-time.mdx

Update block production time

---

docs/tutorial/02-hello-world.md

Hey, @briandoyle81 — Here's the next one, "Hello World".

Edit hello world tutorial

---

docs/tutorial/04-capabilities.md

Hi, @briandoyle81 — This PR edits the Capabilities tutorial: https://cadence-lang.org/docs/tutorial/capabilities
Let me know if you need me to adjust anything and thank you!

Edit capabilities tutorial doc

---

docs/tutorial/05-non-fungible-tokens-2.md

Hi, @briandoyle81 — This PR edits https://cadence-lang.org/docs/tutorial/non-fungible-tokens-2
Thank you!

Edit itermediate nfts tutorial

---

docs/language/values-and-types.mdx

Closes https://github.com/onflow/cadence-lang.org/issues/171, #55.

Add UInt and Int to values-and-types.

---

docs/tutorial/06-fungible-tokens.md

Hi, Brian — This PR edits the Fungible Tokens tutorial: https://cadence-lang.org/docs/tutorial/fungible-tokens
Let me know if you need me to adjust anything. Thank you!

Edit fungible tokens tutorial

---

docs/language/enumerations.md
docs/language/references.mdx

This PR edits the following Language Reference articles:
* [Enumerations](https://cadence-lang.org/docs/language/enumerations)
* [References](https://cadence-lang.org/docs/language/references)

Edit References and Enumerations articles

---

docs/language/crypto.mdx

This article edits the [Crypto](https://cadence-lang.org/docs/language/crypto) article.

Edit Crypto article

---

docs/language/interfaces.mdx

This PR edits the [Interfaces](https://cadence-lang.org/docs/language/interfaces) article.

Edit Interfaces article

---

docs/tutorial/04-capabilities.md

Fixed typo Tutoral

---

docs/tutorial/05-non-fungible-tokens-2.md

Fixed Typo
