onflow/cadence-lang.org

- .gitignore
- pages/community.js
- pages/index.js
Adds a new paragraph in the `Best-In-Class Tooling` section, to list the testing framework & code coverage tools.
> Add more Cadence tooling in docs

- components/navigation.js
Work towards #8 - fixes first issue (second needs to be done in the onflow/docs repo)
> Add Solidity Guide link to the top navigation bar

- versioned_docs/version-1.0/language/accounts/capabilities.mdx
This function was added in onflow/cadence#2778
> Document `Account.Capabilities.exists`

- docusaurus.config.js
work towards https://github.com/onflow/cadence-lang.org/issues/21
This is a quick fix to remove misleading message, ned to come up with a way to customize the docusaurus banner, will do that in a follow-up PR.
> Updating config to remove misleading version banner

- versioned_docs/version-1.0/language/accounts/contracts.mdx
- versioned_docs/version-1.0/language/accounts/index.mdx
- versioned_docs/version-1.0/language/built-in-functions.mdx
- versioned_docs/version-1.0/language/crypto.mdx
- versioned_docs/version-1.0/language/environment-information.md
- versioned_docs/version-1.0/language/run-time-types.md
- versioned_docs/version-1.0/language/values-and-types.mdx
- versioned_docs/version-1.0/testing-framework.mdx
- versioned_docs/version-1.0/tutorial/04-capabilities.md
Work towards https://github.com/onflow/cadence-lang.org/issues/26
> Add view annotations to view library functions

- src/css/custom.css
The move to Docusaurus broke the styling of e.g. links on existing non-documentation pages, like "Community" - they were not colored at all, and looked exactly like normal links ... see e.g. https://cadence-lang.org/community
Restore the styling by removing the scope to the `main` element
> Fix styling

- versioned_docs/version-1.0/language/crypto.mdx
Update `KeyList` example and header with regards to the `verify` function and its new `domainSeparationTag` parameter.
- Side change: remove old call outs of already deployed behaviour
> update KeyList's verify function

- docs/cadence_migration_guide/index.md
A `"` is missing from the Cadence emulator installation command for Windows.
> Fix Windows emulator installation command typo in Cadence 1.0 Migration guide

- docs/cadence_migration_guide/core-contracts-guide.mdx
- docs/cadence_migration_guide/ft-guide.mdx
- docs/cadence_migration_guide/nft-guide.mdx
* Adds a guide that covers all the important things that a developer needs to do to upgrade their NFT contract for Cadence 1.0
* Adds FT specific migration instructions for FT developers.
> Add full NFT migration guide and FT-specific guide

- docs/cadence_migration_guide/core-contracts-guide.mdx
- docs/cadence_migration_guide/ft-guide.mdx
- docs/cadence_migration_guide/nft-guide.mdx
Adds information to the NFT migration guide about important contracts that aren't necessarily core contracts
> add callouts for important contracts

- docs/cadence_migration_guide/index.md
Updates the CI installation instructions to the latest script - I think this is our last outstanding doc that needs updating.
> Update Cadence 1.0 CLI installation doc

- docs/cadence_migration_guide/emulator-state-migration-guide.mdx
Same as https://github.com/onflow/docs/pull/649, Moving it to this repo.
> Add emulator state migration guide

- docs/cadence_migration_guide/emulator-state-migration-guide.mdx
For the time being, add the complete instructions.
Later once https://github.com/onflow/docs/issues/660 is done, we can change this to link that page/section.
> Add CLI installation instructions to the emulator migration guide

- versioned_docs/version-1.0/cadence_migration_guide/nft-guide.mdx
Updates the 1.0 version of the nft migration guide with the changes from [this PR](https://github.com/onflow/cadence-lang.org/pull/75/files) that was already merged.
> Update the 1.0 version of the nft guide

- docs/cadence_migration_guide/nft-guide.mdx
- versioned_docs/version-1.0/cadence_migration_guide/nft-guide.mdx
Fixes the call to `emitNFTUpdated` to use the calling contract's name instead of `NonFungibleToken`
> add clarification about nft updated to the migration guide

- versioned_docs/version-1.0/cadence-migration-guide/nft-guide.mdx
Closes https://github.com/onflow/cadence/issues/3296
The version in the 0.42 section of the docs site already didn't have this, so we only needed to update one of the versions
> Remove Owner entitlement from NFT migration guide

- versioned_docs/version-1.0/cadence-migration-guide/core-contracts-guide.mdx
- versioned_docs/version-1.0/cadence-migration-guide/ft-guide.mdx
- versioned_docs/version-1.0/cadence-migration-guide/nft-guide.mdx
- versioned_docs/version-1.0/design-patterns.md
- versioned_docs/version-1.0/project-development-tips.md
I went through the cadence docs that I manage (except the tutorials) and made sure they made sense with the current versions of the core contracts and my understanding. Also fixed some wording and added import addresses for the testing framework
> Update various docs with latest Cadence 1.0 knowledge

- versioned_docs/version-1.0/json-cadence-spec.md
https://github.com/onflow/cadence/issues/3244
`Restricted` is already removed, so we just need to change `authorized` to `authorizations`
> update cadence 1.0 json specs with Authorization

- versioned_docs/version-1.0/language/syntax.md
> Document reserved identifiers, use 'identifiers' instead of 'names'

- docs/language/crypto.mdx
- versioned_docs/version-1.0/language/crypto.mdx
links in the section [Proof of Possession](https://cadence-lang.org/docs/language/crypto#proof-of-possession-pop) on the `language/crypto` doc site are broken (screenshot below, broken links coloured in green). 
Regarding `Signature verification`:
The problem is simply a typo, where the "S" in the link should _not_ be capitalized. The link should be:
```
https://cadence-lang.org/docs/language/crypto#signature-verification 
```
Regarding `serialization details`:
I am not entirely sure where the link should point to. The [PublicKey](https://cadence-lang.org/docs/language/crypto#publickey) section is pretty long. I would suggest to link directly to the sub-section [Public Key construction](https://cadence-lang.org/docs/language/crypto#public-key-construction):
``` …
```
> fix broken links in Proof of Possession paragraph on the crypto page

- versioned_docs/version-1.0/cadence-migration-guide/usdc-migration.mdx
Adds a first draft of the USDC migration guide for users and developers.
It is probably missing some cases, but it is a good enough place to start. I'll be adding more to it in the coming days but it would be good to get something up for it for now so people can get started.
> First draft of USDC migration guide

- docs/tutorial/01-first-steps.md
- docs/tutorial/02-hello-world.md
- docs/tutorial/03-resources.md
- docs/tutorial/04-capabilities.md
- docs/tutorial/05-non-fungible-tokens-1.md
- docs/tutorial/05-non-fungible-tokens-2.md
- docs/tutorial/06-fungible-tokens.md
- docs/tutorial/07-marketplace-setup.md
- docs/tutorial/08-marketplace-compose.md
- docs/tutorial/09-voting.md
- docs/tutorial/10-resources-compose.md
All the tutorial links are broken right now, so I've updated the first four tutorials and fixed the import addresses for the rest of them to at least have something that is somewhat working on the docs site right now.
I'd like to merge this ASAP if possible
I'll be going through and updating the rest in the next few days.
> Replace links for first 4 tutorials and update import addresses

- docs/tutorial/04-capabilities.md
- docs/tutorial/05-non-fungible-tokens-2.md
- docs/tutorial/06-fungible-tokens.md
- docs/tutorial/ExampleToken.cdc
Updates the NFT and FT tutorials after being able to test with them
Adds `ExampleToken.cdc` as a reference since it isn't shown in the tutorial
> Fix NFT and FT tutorials

- docs/json-cadence-spec.md
- docs/language/environment-information.md
- docs/solidity-to-cadence.md
- docs/tutorial/08-marketplace-compose.md
Work towards #48
@joshuahannan could you (or maybe @sisyphusSmiling) please fix the Solidity guide? 🙏
> Fix mentions of PublicAccount and AuthAccount

- docs/language/syntax.md
The `result` keyword was missing from the list of reserved identifiers. This PR adds the keyword to the list.
> Add `result` to reserved identifiers

- src/theme/MDXComponents.js
With #164 merged, `Callout` or `Admonition` components should not be used directly anymore, so remove the mapping for them.
> Remove Callout and Admonition mapping

- docs/language/accounts/keys.mdx
Clarify the restriction about the crypto algorithms supported by an account key in Cadence/Flow. 
This has been causing confusion for example in https://github.com/onflow/flow-core-contracts/issues/460, and is only mentioned in the [Node API doc](https://developers.flow.com/build/basics/accounts#signature-and-hash-algorithms).
> Update account keys

- docs/tutorial/03-resources.md
- docs/tutorial/05-non-fungible-tokens-1.md
- src/css/custom.css
Hi, @briandoyle81 — This PR edits the Basic NFT tutorial: https://cadence-lang.org/docs/tutorial/non-fungible-tokens-1
Also, this PR includes a small addition to the custom.css file, which when added, will make all of the numbering appear in ordered lists within the Cadence-lang tutorials.
Let me know if you have any questions!
> Edit basic NFT tutorial

- docs/language/constants-and-variables.md
- docs/language/index.md
- docs/language/syntax.md
Hi, Brian — This PR edits the first three articles In the Language Reference section:
* https://cadence-lang.org/docs/language/
* https://cadence-lang.org/docs/language/syntax
* https://cadence-lang.org/docs/language/constants-and-variables
Talk to you soon!
> Edit first three lang ref articles

- docs/tutorial/03-resources.md
This is a breaking bug from one of the intro do cadence tutorials.  It threw me off pretty early on in the learning Cadence process so think its important to patch it up.  The accompanying code in the flow playground also have this bug so the links within the tutorial that take you to those supplied code snippets in the playground should be fixed as well.
> Change & to @ in storage.check

- docs/cadence-migration-guide/improvements.md
- docs/cadence-migration-guide/index.md
This PR edits the following Cadence 1.0 Migration Guides:
* [Index](https://cadence-lang.org/docs/cadence-migration-guide/)
* [Improvements & New Features](https://cadence-lang.org/docs/cadence-migration-guide/improvements)
> Edit first two Cadence Migration Guides
